-   id: poetry-lock-file
    name: poetry locked
    description: "Check if poetry is locked and updated"
    entry: poetry-lock
    language: python
    verbose: True
    files: pyproject.*
    minimum_pre_commit_version: 0.15.0
