- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.4.0
  hooks:
  -   id: trailing-whitespace
  -   id: end-of-file-fixer
  -   id: check-docstring-first
  -   id: check-yaml
  -   id: debug-statements
  -   id: name-tests-test
  -   id: flake8

- repo: https://github.com/pre-commit/pre-commit
  rev: v1.7.0
  hooks:
  -   id: validate_manifest

- repo: https://github.com/ambv/black
  rev: master
  hooks:
  -   id: black
